set(headers ${headers}
	src/Cache.h
	src/Console.h
	src/ENB/AntTweakBar.h
	src/ENB/ENB.h
	src/ENB/ENBSeriesAPI.h
	src/ENB/ENBSeriesSDK.h
	src/Graphics.h
	src/Hooks.h
	src/ImGui/FormComboBox.h
	src/ImGui/Graphics.h
	src/ImGui/IconsFontAwesome6.h
	src/ImGui/IconsFonts.h
	src/ImGui/Renderer.h
	src/ImGui/Styles.h
	src/ImGui/Util.h
	src/ImGui/Widgets.h
	src/Input.h
	src/PCH.h
	src/Papyrus.h
	src/PhotoMode/Hotkeys.h
	src/PhotoMode/Manager.h
	src/PhotoMode/Tabs/Camera.h
	src/PhotoMode/Tabs/CameraPositions.h
	src/PhotoMode/Tabs/Character.h
	src/PhotoMode/Tabs/Filters.h
	src/PhotoMode/Tabs/Overlays.h
	src/PhotoMode/Tabs/Time.h
	src/Screenshots/LoadScreen.h
	src/Screenshots/Manager.h
	src/Settings.h
	src/Translation.h
)
