set(headers ${headers}
	src/Cache.h
	src/ImGui/FormComboBox.h
	src/ImGui/Icons.h
	src/ImGui/IconsFontAwesome6.h
	src/ImGui/Renderer.h
	src/ImGui/Util.h
	src/Input.h
	src/PCH.h
	src/PhotoMode/Camera.h
	src/PhotoMode/Filters.h
	src/PhotoMode/Manager.h
	src/PhotoMode/Player.h
	src/PhotoMode/Time.h
	src/Screenshots/LoadScreen.h
	src/Screenshots/Manager.h
	src/Settings.h
	src/Textures.h
	src/Translation.h
)
