set(sources ${sources}
	src/ImGui/Icons.cpp
	src/ImGui/Renderer.cpp
	src/ImGui/Util.cpp
	src/Input.cpp
	src/PCH.cpp
	src/Papyrus.cpp
	src/PhotoMode/Camera.cpp
	src/PhotoMode/Filters.cpp
	src/PhotoMode/Manager.cpp
	src/PhotoMode/Player.cpp
	src/PhotoMode/Time.cpp
	src/Screenshots/LoadScreen.cpp
	src/Screenshots/Manager.cpp
	src/Settings.cpp
	src/Textures.cpp
	src/Translation.cpp
	src/main.cpp
)
