set(sources ${sources}
	src/Hooks.cpp
	src/ImGui/IconsFonts.cpp
	src/ImGui/Renderer.cpp
	src/ImGui/Util.cpp
	src/Input.cpp
	src/PCH.cpp
	src/Papyrus.cpp
	src/PhotoMode/Hotkeys.cpp
	src/PhotoMode/Manager.cpp
	src/PhotoMode/Tabs/Camera.cpp
	src/PhotoMode/Tabs/Filters.cpp
	src/PhotoMode/Tabs/Player.cpp
	src/PhotoMode/Tabs/Time.cpp
	src/Screenshots/LoadScreen.cpp
	src/Screenshots/Manager.cpp
	src/Settings.cpp
	src/Textures.cpp
	src/Translation.cpp
	src/main.cpp
)
